# Debug模式
# 非开发者可以关闭
Debug_Mode: true


# 服务器的名称
# 请根据实际情况修改，将在很多地方应用到
# 可以用&代替§，本插件会自动转义
Server_Name: "&bStar&eLight"


# 是否启用正版认证功能
# 正版认证功能，是一项让持有正版玩家更快乐的功能（对离线登录/皮肤站登录的玩家没有影响）
# 它可以配合服务器的总入口（通常是一个BungeeCord或者Velocity），对部分玩家启用正版认证
# 一旦这些玩家通过正版认证，即为其启用免密登录（仅兼容AuthMe）
# 但请注意，该功能的正常使用，必须配合服务器总入口的相关接口实现
# 如果缺少这个实现，服务器将会产生误判，从而大大提高玩家被盗号的风险
# 因此如果您缺少相关的实现，或不懂得如何实现，请不要启用这个功能
Enable_Online_Mode: true


# 是否启用图像消息模式
# 图像消息模式会尽可能将消息转化为图片发送
# 这通常可以有效避免风控，并且让消息看起来更好看
# 但是会消耗更多的性能，并且可能需要您额外添加浏览器的二进制文件与驱动文件
# 建议在低配服务器上不要启用该选项
Enable_Image_Msg: false


# 使用的复杂图片生成器
# 在渲染颜色与元素比较复杂的图片时会应用到，工作原理的借助浏览器的Render解析并渲染HTML
# （你的计算机中浏览器喜+1）
# 仅在开启图像消息模式后，本选项才可以生效
# 默认（DEFAULT）为CHROME
# 可用值：CHROME（基于Chrome的Render），FIREFOX（基于Firefox的Render）
# 为防止插件体积过大，本插件不集成任何浏览器的二进制文件，若有需要，可以额外下载
Image_Generator: "DEFAULT"


# 是否在邀请的时候发送一张图片，可用于发送加群二维码等图片
Send_Pic_While_Invite: true

# WebSocket服务器监听地址
WS_Server_Port: 16123  # 服务器自带的Websocket服务端端口
WS_Bot_Port: 16124  # Bot端（需要支持OneBot规范）的Websocket端口


# 广播Token，在发送广播信息时用于鉴权
Announce_Token: null

# 服务器群：
Exam_Server_Group: 535392227  # 服务器审核群，会t出已经通过审核的成员
Main_Server_Group: 755804021  # 主服务器群，插件会监听该群的所有情况（包括用户入群与退群）
Bind_Only_Group:  # 仅允许绑定/删除ID的群，可以用于测试，请将主服务器群一并包含于此！！！
  - 755804021
  - 869989212
  - 1134701006
  - 128122335
Review_Group: 869989212  # 审核专用群，用于发送一些审核状态消息
Internal_Server_Group:  # 内服群，允许内服的一些操作
  - 128122335

# 服务器相关信息：
Owner_QQ: # 腐竹的QQ（会成为机器人的主人）
  - 1481567451
Admins_QQ:  # 管理员(们)的QQ
  - 1481567451
Internal_Admins_QQ:  # 内服管理员(们)的QQ
  - 1481567451

# 各种消息的配置文件：

# 踢出不在白名的玩家时显示的信息
Kick_Message: "§d§l[StarLight服务器]§6§l你好像还没有绑定过你的ID
请加入我们的QQ群:§b535392227
§6§l并在群里发送§e“#绑定ID:你的ID”
§l§6即可§a正常§6进入服务器了哦！"

# 提示去做审核题时机器人发送的消息
Require_Exam_Message: "你好像还没通过审核哦！先去做一下审核题吧！审核题传送门：https://ks.wjx.top/vj/w6ktU8L.aspx"

# 审核通过时私聊玩家的提示信息
Exam_Passed_Message: "你的审核已通过！现在可以联系审核员将你拉入服务器群啦！"